import React, { useState, useEffect } from 'react';
import { SuratKeluar, KodeKlasifikasi, SifatSurat, InstansiConfig, StatusSuratKeluar } from '../types';
import { formatDateDDMMYYYY } from '../utils/dateUtils';
import { X, Save, Send, FileText, Sparkles, Edit } from 'lucide-react';

interface FormSuratKeluarProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (data: Omit<SuratKeluar, 'id' | 'createdAt'>) => void;
  onUpdate?: (id: string, data: Partial<SuratKeluar>) => void;
  kodeKlasifikasiList: KodeKlasifikasi[];
  instansiConfig: InstansiConfig;
  nextAgendaNo: string;
  editData?: SuratKeluar | null;
}

export const FormSuratKeluar: React.FC<FormSuratKeluarProps> = ({
  isOpen,
  onClose,
  onSubmit,
  onUpdate,
  kodeKlasifikasiList,
  instansiConfig,
  nextAgendaNo,
  editData,
}) => {
  const today = new Date().toISOString().split('T')[0];
  const isEdit = Boolean(editData);

  const [noAgenda, setNoAgenda] = useState(nextAgendaNo);
  const [kodeKlasifikasi, setKodeKlasifikasi] = useState(kodeKlasifikasiList[0]?.kode || '005');
  const [sifatSurat, setSifatSurat] = useState<SifatSurat>('Penting');
  const [tglSurat, setTglSurat] = useState(today);
  const [tujuan, setTujuan] = useState('');
  const [perihal, setPerihal] = useState('');
  const [isiSurat, setIsiSurat] = useState(
    'Dalam rangka pelaksanaan program kerja dan peningkatan kinerja instansi, bersama ini disampaikan permohonan/pemberitahuan sebagaimana perihal di atas.\n\nDemikian disampaikan, atas perhatian dan kerja samanya diucapkan terima kasih.'
  );
  const [penandatangan, setPenandatangan] = useState(instansiConfig.namaKepala);
  const [status, setStatus] = useState<StatusSuratKeluar>('Draft');
  const [customNoSurat, setCustomNoSurat] = useState<string>('');

  useEffect(() => {
    if (editData) {
      setNoAgenda(editData.noAgenda);
      setKodeKlasifikasi(editData.kodeKlasifikasi);
      setSifatSurat(editData.sifatSurat);
      setTglSurat(editData.tglSurat);
      setTujuan(editData.tujuan);
      setPerihal(editData.perihal);
      setIsiSurat(editData.isiSurat);
      setPenandatangan(editData.penandatangan);
      setStatus(editData.status);
      setCustomNoSurat(editData.noSurat);
    } else {
      setNoAgenda(nextAgendaNo);
      setKodeKlasifikasi(kodeKlasifikasiList[0]?.kode || '005');
      setSifatSurat('Penting');
      setTglSurat(today);
      setTujuan('');
      setPerihal('');
      setIsiSurat(
        'Dalam rangka pelaksanaan program kerja dan peningkatan kinerja instansi, bersama ini disampaikan permohonan/pemberitahuan sebagaimana perihal di atas.\n\nDemikian disampaikan, atas perhatian dan kerja samanya diucapkan terima kasih.'
      );
      setPenandatangan(instansiConfig.namaKepala);
      setStatus('Draft');
      setCustomNoSurat('');
    }
  }, [isOpen, editData, nextAgendaNo, instansiConfig.namaKepala]);

  if (!isOpen) return null;

  // Auto-formatted letter number logic
  const numOnly = noAgenda.split('/')[0] || '101';
  const formatTemplate = instansiConfig.formatNomorSuratKeluar || '{kode}/{no}/{instansi}/{tahun}';
  const kodeSandi = instansiConfig.kodeSandiInstansi || 'DISKOMINFO-SS';
  const autoGeneratedNoSurat = formatTemplate
    .replace('{kode}', kodeKlasifikasi)
    .replace('{no}', numOnly)
    .replace('{instansi}', kodeSandi)
    .replace('{tahun}', String(new Date().getFullYear()));

  const finalNoSurat = customNoSurat.trim() || autoGeneratedNoSurat;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!tujuan.trim() || !perihal.trim() || !isiSurat.trim()) {
      alert('Mohon lengkapi Tujuan, Perihal, dan Isi Surat!');
      return;
    }

    const payload = {
      noAgenda,
      noSurat: finalNoSurat,
      tglSurat,
      tujuan,
      perihal,
      isiSurat,
      kodeKlasifikasi,
      sifatSurat,
      status,
      penandatangan,
    };

    if (isEdit && editData && onUpdate) {
      onUpdate(editData.id, payload);
    } else {
      onSubmit(payload);
    }

    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4 overflow-y-auto">
      <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full border border-slate-200 overflow-hidden my-8 animate-in fade-in zoom-in duration-200">
        
        {/* Header */}
        <div className="bg-gradient-to-r from-emerald-800 to-teal-900 text-white p-5 flex items-center justify-between">
          <div className="flex items-center space-x-2">
            {isEdit ? <Edit className="w-5 h-5 text-emerald-300" /> : <Send className="w-5 h-5 text-emerald-300" />}
            <div>
              <h2 className="text-lg font-bold">{isEdit ? 'Edit Agenda Surat Keluar' : 'Buat Draft Naskah Surat Keluar'}</h2>
              <p className="text-xs text-emerald-200">
                {isEdit ? `Pengubahan rincian naskah surat keluar (${noAgenda})` : 'Format standar penomoran naskah dinas resmi'}
              </p>
            </div>
          </div>
          <button 
            type="button"
            onClick={onClose}
            className="text-emerald-200 hover:text-white p-1 rounded-lg hover:bg-white/10 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form Body */}
        <form onSubmit={handleSubmit} className="p-6 space-y-4 max-h-[80vh] overflow-y-auto text-xs">
          
          {/* Format No Surat Auto Preview */}
          <div className="bg-emerald-50 border border-emerald-200 p-3 rounded-lg flex items-center justify-between">
            <div>
              <span className="text-[10px] font-bold text-emerald-800 uppercase tracking-wider block">Format Nomor Surat Otomatis</span>
              <span className="text-sm font-bold font-mono text-emerald-950">{finalNoSurat}</span>
            </div>
            <Sparkles className="w-5 h-5 text-emerald-600 animate-pulse" />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Agenda No */}
            <div>
              <label className="block font-bold text-slate-700 mb-1">Nomor Agenda Surat Keluar *</label>
              <input
                type="text"
                value={noAgenda}
                onChange={(e) => setNoAgenda(e.target.value)}
                required
                className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg font-mono font-bold text-slate-800 focus:ring-2 focus:ring-emerald-500"
              />
            </div>

            {/* Kode Klasifikasi */}
            <div>
              <label className="block font-bold text-slate-700 mb-1">Kode Klasifikasi Surat *</label>
              <select
                value={kodeKlasifikasi}
                onChange={(e) => setKodeKlasifikasi(e.target.value)}
                className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg font-medium text-slate-800 focus:ring-2 focus:ring-emerald-500"
              >
                {kodeKlasifikasiList.map((k) => (
                  <option key={k.kode} value={k.kode}>
                    {k.kode} - {k.nama}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Tanggal Surat */}
            <div>
              <div className="flex justify-between items-center mb-1">
                <label className="block font-bold text-slate-700">Tanggal Surat *</label>
                <span className="text-[10px] text-emerald-700 font-bold bg-emerald-50 px-1.5 py-0.5 rounded border border-emerald-200 font-mono">
                  {formatDateDDMMYYYY(tglSurat)}
                </span>
              </div>
              <input
                type="date"
                value={tglSurat}
                onChange={(e) => setTglSurat(e.target.value)}
                required
                className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg text-slate-800 focus:ring-2 focus:ring-emerald-500"
              />
            </div>

            {/* Sifat Surat */}
            <div>
              <label className="block font-bold text-slate-700 mb-1">Sifat Surat *</label>
              <select
                value={sifatSurat}
                onChange={(e) => setSifatSurat(e.target.value as SifatSurat)}
                className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg font-medium text-slate-800 focus:ring-2 focus:ring-emerald-500"
              >
                <option value="Biasa">Biasa</option>
                <option value="Penting">Penting</option>
                <option value="Sangat Penting">Sangat Penting</option>
                <option value="Rahasia">Rahasia</option>
              </select>
            </div>
          </div>

          {/* Tujuan Surat */}
          <div>
            <label className="block font-bold text-slate-700 mb-1">Tujuan / Kepada Yth. *</label>
            <input
              type="text"
              value={tujuan}
              onChange={(e) => setTujuan(e.target.value)}
              placeholder="Contoh: Kepala Bappeda Provinsi Sulawesi Selatan"
              required
              className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg font-medium text-slate-800 focus:ring-2 focus:ring-emerald-500"
            />
          </div>

          {/* Perihal */}
          <div>
            <label className="block font-bold text-slate-700 mb-1">Perihal Surat Keluar *</label>
            <input
              type="text"
              value={perihal}
              onChange={(e) => setPerihal(e.target.value)}
              placeholder="Contoh: Undangan Workshop Akselerasi Digital"
              required
              className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg font-medium text-slate-800 focus:ring-2 focus:ring-emerald-500"
            />
          </div>

          {/* Isi Naskah Surat */}
          <div>
            <label className="block font-bold text-slate-700 mb-1">Isi Naskah Surat *</label>
            <textarea
              value={isiSurat}
              onChange={(e) => setIsiSurat(e.target.value)}
              rows={5}
              required
              className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg text-slate-800 focus:ring-2 focus:ring-emerald-500 font-mono text-[11px]"
            />
          </div>

          {/* Penandatangan */}
          <div>
            <label className="block font-bold text-slate-700 mb-1">Nama Pejabat Penandatangan *</label>
            <input
              type="text"
              value={penandatangan}
              onChange={(e) => setPenandatangan(e.target.value)}
              required
              className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg font-semibold text-slate-800 focus:ring-2 focus:ring-emerald-500"
            />
          </div>

          {/* Buttons */}
          <div className="pt-4 border-t border-slate-200 flex items-center justify-end space-x-3">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-lg font-semibold text-slate-600 bg-slate-100 hover:bg-slate-200 transition-colors cursor-pointer"
            >
              Batal
            </button>
            <button
              type="submit"
              className="px-5 py-2 rounded-lg font-bold text-white bg-emerald-600 hover:bg-emerald-700 shadow-md transition-all flex items-center space-x-1.5 cursor-pointer"
            >
              <Save className="w-4 h-4" />
              <span>{isEdit ? 'Simpan Perubahan Surat Keluar' : 'Simpan Draft Surat Keluar'}</span>
            </button>
          </div>

        </form>

      </div>
    </div>
  );
};
